# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            SOC401 DS Project
tagline:          ''
description:      'A data science for social good project at the University of Washington'
url:              "https://sixing-tao.github.io"
baseurl:          "/25au_SOC401_DS_Project"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/sixing-tao/25au_SOC401_DS_Project
